# Site Information
title: "Ver처nica M채ki-Marttunen's Research on Brain Dynamics"
author: "Ver처nica M채ki-Marttunen"
description: "Slow brain dynamics, neuromodulation, and behavior"
lang: "en"
date_format: "%B %d, %Y"

# Permalink Configuration
permalink: /:title/
excerpt_separator: "\n\n\n"

# Layout Options
show_excerpts: false             # Show article excerpts instead of an archive list on the home page
show_frame: true                 # Display a grey frame on large screens
show_sidebar: false               # Show a sidebar instead of the usual header
show_minimal: false              # Remove all clutter

# Menu Configuration
navigation:                     # Accepts {file, title, url, icon, sidebaricon}
  - {file: "research.md", title: "Research"} # , sidebaricon: home
  - {file: "cv.md", title: "CV"} # , sidebaricon: address-card
  - {file: "blog.md", title: "Blog", sidebaricon: home}

external:                       # Accepts {file, title, url, icon, sidebaricon}
  - {title: "Mail", icon: "envelope", url: "mailto:veroniex@uio.no"}
  - {title: "GitHub", icon: "github", url: "https://github.com/VeronicaMaki-Marttunen"}
  - {title: "LinkedIn", icon: "rss", url: "https://www.linkedin.com/in/veronicamaekimarttunen/"}

# Comments Configuration
comments:
  # disqus_shortname: ""         # See https://disqus.com
  # isso_domain: ""              # See https://isso-comments.de

# Plugins Configuration
plugins:
  - jekyll-feed
